config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants do
    resources :reservations
    resources :reviews, :only => [:create]
  end
  resources :sessions, :only => [:create, :destroy]

  root 'home#index'

  get '/login' => 'sessions#new'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :time, :num_of_seats, :presence => true

  before_save :check_capacity

  private

  def check_capacity
    restaurant.available?(num_of_seats, time, date)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
  has_many :reviews
  has_many :users, :through => :reservations

  validates :name, :seats, :open, :close, :presence => true

  def open_hours
    (open...close).to_a
  end

  def available?(num_of_seats, time, date)
    reservations_for_time = reservations.where(time: time, date: date)
    reservations_for_time.sum(:num_of_seats) + num_of_seats <= seats
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :title, :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, :presence => true
  validates :email, :uniqueness => true

  has_many :restaurants
  has_many :reservations
  has_many :restaurants, :through => :reservations

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      redirect_to login_url
    end
  end

  def user_owner
    unless current_user.id == params[:id].to_i
      redirect_to restaurants_url
    end
  end

  def restaurant_owner
    unless current_user.id == Restaurant.find(params[:id]).user_id.to_i
      redirect_to restaurants_url
    end
  end

  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to restaurant_url(@restaurant), :notice => 'Reservation Successfully Made'
    else
      redirect_to restaurant_url(@restaurant), :alert => 'Reservation not available for the number requested.'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to user_url(current_user)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:num_of_seats, :time, :date)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_filter :restaurant_owner, :only => [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.all

    if current_user
      @reservation = @restaurant.reservations.build
    end
    
    if current_user
      @review = @restaurant.reviews.build
    end

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_url(@restaurant)
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @user = current_user
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_url(@restaurant)
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :seats, :open, :close, :address, :image_url, :description, :website)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_restaurant

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_url(@restaurant), :notice => 'Review successfully created'
    else
      redirect_to restaurant_url(@restaurant), :alert => 'Review did not save. Please try again.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_url(user), :notice => 'Successfully logged in'
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :user_owner, :only => [:create, :edit, :destroy, :update, :show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

    @restaurants = @user.restaurants
    @reservations = @user.reservations
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :about, :avatar_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def m_to_st(h)
    if h > 12
      (h-12).to_s + ":00 PM"
    elsif h == 12
      h.to_s + ":00 PM"
    else
      h.to_s + ":00 AM"
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <%= link_to "See Restaurants", restaurants_path, :class => 'btn btn-cta' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to "SeatYourself", root_path %>
    <nav>
      <% if current_user %>
        <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user), :class => 'btn' %> <%= link_to "New Restaurant", new_restaurant_path, :class => 'btn' %> <%= link_to "Logout", session_path("current"), :method => :delete, :class => 'btn' %>
      <% else %>
        <%= link_to  "Sign Up", new_user_path, :class => 'btn btn-signup' %>
        <%= link_to "Login", login_path, :class => 'btn' %>
      <% end %>
      <%= link_to "Restaurant Listings", restaurants_path, :class => 'btn' %>
    </nav>
  </header>
  <main>
  <% if flash[:notice] %>
    <p class='flash flash-notice'><%= flash[:notice] %></p>
  <% elsif flash[:alert] %>
    <p class='flash flash-error'><%= flash[:alert] %></p>
  <% end %>

    <%= yield %>
  </main>
</body>
</html>

app/views/reservations/_form.html.erb
<% if current_user %>
  <%= form_for([@restaurant, @reservation], :html => {:class => 'reservation', :id => 'reservation'}) do |f| %>
    <%= f.label :num_of_seats %>
    <%= f.number_field :num_of_seats %>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <div class="times">
      <% @restaurant.open_hours.each do |h| %>
        <%= f.radio_button(:time, h, class: "hidden") %>
        <%= f.label "time_#{h}", 
          m_to_st(h), 
        class: "reserve" %>
      <% end %>
    </div>
    <%= f.button "Reserve Now", :class => 'btn btn-cta' %>
  <% end %>
<% else %>
  <%= link_to "Login to Make a Reservation", login_path, :class => 'btn btn-cta' %>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.label :seats %>
  <%= f.number_field :seats %>
  <%= f.label :open %>
  <%= f.number_field :open %>
  <%= f.label :close %>
  <%= f.number_field :close %>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.button :class => 'btn btn-login' %>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class ="restaurant-card">
    <div class="restaurant-info">
      <h3><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h3>
      <hr>
      <p><%= restaurant.address %></p>
      <%= link_to "View Restaurant", restaurant_path(restaurant), :class => 'btn btn-login' %>
    </div>
    <%= image_tag restaurant.image_url, :class => 'thumbnail' %>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="jumbotron jumbotron-restaurant" style='background: url(<%= @restaurant.image_url %>)'>

<% if current_user %>
  <%= form_for([@restaurant, @reservation], :html => {:class => 'reservation'}) do |f| %>
    <%= f.label :num_of_seats %>
    <%= f.number_field :num_of_seats, in: 1..50, value: 1 %>
    <%= f.label :date %>
    <%= f.date_field :date, value: Date.today %>
    <div class="times">
      <% @restaurant.open_hours.each do |h| %>
        <%= f.radio_button(:time, h, class: "hidden") %>
        <%= f.label "time_#{h}", 
          m_to_st(h), 
        class: "reserve" %>
      <% end %>
    </div>
    <%= f.button "Reserve Now", :class => 'btn btn-cta' %>
  <% end %>
<% else %>
  <%= link_to "Login to Make a Reservation", login_path, :class => 'btn btn-cta' %>
<% end %>

</div>

<div class="restaurant">
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p>Website:</p>
  <p>Open: <%= m_to_st(@restaurant.open) %></p>
  <p>Close: <%= m_to_st(@restaurant.close) %></p>
  <%= @restaurant.description %>

  <% if current_user.id == @restaurant.user_id %>
    <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), :class => 'btn' %>
    <%= link_to "Delete Restaurant", restaurant_path(@restaurant), :method => :delete, :class => 'btn' %>
  <% end %>
  <h2>Reviews</h2>

  <% @reviews.each do |review| %>
    <p><%= review.title %></p>
    <p><%= review.content %></p>
    <p><%= User.find(review.user_id).first_name %> <%= User.find(review.user_id).last_name %></p>
  <% end %>

  <h2>Add New Review</h2>
  <% if current_user %>
    <%= form_for([@restaurant, @review], :html => {:class => 'review'}) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.button 'Add Review', :class => 'btn btn-login' %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit your Profile</h1>
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :avatar_url %>
  <%= f.text_field :avatar_url %>
  <%= f.label :about %>
  <%= f.text_area :about %>
  <%= f.button "Update" %>
<% end %>

app/views/users/new.html.erb
<h2>Sign up now</h2>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.button "Sign Up Now!", :class => 'btn btn-signup' %>
<% end %>

app/views/users/show.html.erb
<div class="user-wrapper">
  <div class="sidebar">
    <%= image_tag @user.avatar_url, :class => 'avatar' %>
    <ul>
      <li><h2><%= @user.first_name %> <%= @user.last_name %></h2></li>
      <li><%= @user.created_at %></li>
      <li><%= link_to "Edit Profile", edit_user_path(@user) %></li>
      <li><%= link_to "Create Restaurant", new_restaurant_path %></li>
    </ul>
  </div>
  <div class="article">
    <h2>About</h2>
    <%= @user.about %>

    <h2>Reservations</h2>
      <ul>
      <% @reservations.each do |reservation| %>
        <li>Where: <%= reservation.restaurant.name %></li> 
        <li>When:<%= m_to_st(reservation.time) %> <%= reservation.date %></li>
        <li>For: <%= reservation.num_of_seats %></li>
      <% end %>
    </ul>
  </div>
</div>